package model.EO;

import oracle.jbo.server.ApplicationModuleDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 27 08:17:04 GST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleDefImpl extends ApplicationModuleDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleDefImpl() {
    }
}

