package model.VO;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 28 08:03:22 GST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocumentDetailsViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_DOCUMENTDETAILS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Doccontentid,
        Doccreatedby,
        Doccreateddate,
        Docdid,
        Docoriginalname,
        Docsize,
        Docformat,
        Doctitle,
        Doccontenttype,
        Docmodifiedby,
        Docmodifieddate,
        Docsecuritygroup,
        Docsourceaccount,
        Documenturl;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DOCCONTENTID = AttributesEnum.Doccontentid.index();
    public static final int DOCCREATEDBY = AttributesEnum.Doccreatedby.index();
    public static final int DOCCREATEDDATE = AttributesEnum.Doccreateddate.index();
    public static final int DOCDID = AttributesEnum.Docdid.index();
    public static final int DOCORIGINALNAME = AttributesEnum.Docoriginalname.index();
    public static final int DOCSIZE = AttributesEnum.Docsize.index();
    public static final int DOCFORMAT = AttributesEnum.Docformat.index();
    public static final int DOCTITLE = AttributesEnum.Doctitle.index();
    public static final int DOCCONTENTTYPE = AttributesEnum.Doccontenttype.index();
    public static final int DOCMODIFIEDBY = AttributesEnum.Docmodifiedby.index();
    public static final int DOCMODIFIEDDATE = AttributesEnum.Docmodifieddate.index();
    public static final int DOCSECURITYGROUP = AttributesEnum.Docsecuritygroup.index();
    public static final int DOCSOURCEACCOUNT = AttributesEnum.Docsourceaccount.index();
    public static final int DOCUMENTURL = AttributesEnum.Documenturl.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DocumentDetailsViewRowImpl() {
    }

    /**
     * Gets DocumentDetails entity object.
     * @return the DocumentDetails
     */
    public EntityImpl getDocumentDetails() {
        return (EntityImpl) getEntity(ENTITY_DOCUMENTDETAILS);
    }

    /**
     * Gets the attribute value for DOCCONTENTID using the alias name Doccontentid.
     * @return the DOCCONTENTID
     */
    public String getDoccontentid() {
        return (String) getAttributeInternal(DOCCONTENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCCONTENTID using the alias name Doccontentid.
     * @param value value to set the DOCCONTENTID
     */
    public void setDoccontentid(String value) {
        setAttributeInternal(DOCCONTENTID, value);
    }

    /**
     * Gets the attribute value for DOCCREATEDBY using the alias name Doccreatedby.
     * @return the DOCCREATEDBY
     */
    public String getDoccreatedby() {
        return (String) getAttributeInternal(DOCCREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCCREATEDBY using the alias name Doccreatedby.
     * @param value value to set the DOCCREATEDBY
     */
    public void setDoccreatedby(String value) {
        setAttributeInternal(DOCCREATEDBY, value);
    }

    /**
     * Gets the attribute value for DOCCREATEDDATE using the alias name Doccreateddate.
     * @return the DOCCREATEDDATE
     */
    public String getDoccreateddate() {
        return (String) getAttributeInternal(DOCCREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCCREATEDDATE using the alias name Doccreateddate.
     * @param value value to set the DOCCREATEDDATE
     */
    public void setDoccreateddate(String value) {
        setAttributeInternal(DOCCREATEDDATE, value);
    }

    /**
     * Gets the attribute value for DOCDID using the alias name Docdid.
     * @return the DOCDID
     */
    public String getDocdid() {
        return (String) getAttributeInternal(DOCDID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCDID using the alias name Docdid.
     * @param value value to set the DOCDID
     */
    public void setDocdid(String value) {
        setAttributeInternal(DOCDID, value);
    }

    /**
     * Gets the attribute value for DOCORIGINALNAME using the alias name Docoriginalname.
     * @return the DOCORIGINALNAME
     */
    public String getDocoriginalname() {
        return (String) getAttributeInternal(DOCORIGINALNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCORIGINALNAME using the alias name Docoriginalname.
     * @param value value to set the DOCORIGINALNAME
     */
    public void setDocoriginalname(String value) {
        setAttributeInternal(DOCORIGINALNAME, value);
    }

    /**
     * Gets the attribute value for DOCSIZE using the alias name Docsize.
     * @return the DOCSIZE
     */
    public String getDocsize() {
        return (String) getAttributeInternal(DOCSIZE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCSIZE using the alias name Docsize.
     * @param value value to set the DOCSIZE
     */
    public void setDocsize(String value) {
        setAttributeInternal(DOCSIZE, value);
    }

    /**
     * Gets the attribute value for DOCFORMAT using the alias name Docformat.
     * @return the DOCFORMAT
     */
    public String getDocformat() {
        return (String) getAttributeInternal(DOCFORMAT);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCFORMAT using the alias name Docformat.
     * @param value value to set the DOCFORMAT
     */
    public void setDocformat(String value) {
        setAttributeInternal(DOCFORMAT, value);
    }

    /**
     * Gets the attribute value for DOCTITLE using the alias name Doctitle.
     * @return the DOCTITLE
     */
    public String getDoctitle() {
        return (String) getAttributeInternal(DOCTITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCTITLE using the alias name Doctitle.
     * @param value value to set the DOCTITLE
     */
    public void setDoctitle(String value) {
        setAttributeInternal(DOCTITLE, value);
    }

    /**
     * Gets the attribute value for DOCCONTENTTYPE using the alias name Doccontenttype.
     * @return the DOCCONTENTTYPE
     */
    public String getDoccontenttype() {
        return (String) getAttributeInternal(DOCCONTENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCCONTENTTYPE using the alias name Doccontenttype.
     * @param value value to set the DOCCONTENTTYPE
     */
    public void setDoccontenttype(String value) {
        setAttributeInternal(DOCCONTENTTYPE, value);
    }

    /**
     * Gets the attribute value for DOCMODIFIEDBY using the alias name Docmodifiedby.
     * @return the DOCMODIFIEDBY
     */
    public String getDocmodifiedby() {
        return (String) getAttributeInternal(DOCMODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCMODIFIEDBY using the alias name Docmodifiedby.
     * @param value value to set the DOCMODIFIEDBY
     */
    public void setDocmodifiedby(String value) {
        setAttributeInternal(DOCMODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for DOCMODIFIEDDATE using the alias name Docmodifieddate.
     * @return the DOCMODIFIEDDATE
     */
    public String getDocmodifieddate() {
        return (String) getAttributeInternal(DOCMODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCMODIFIEDDATE using the alias name Docmodifieddate.
     * @param value value to set the DOCMODIFIEDDATE
     */
    public void setDocmodifieddate(String value) {
        setAttributeInternal(DOCMODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for DOCSECURITYGROUP using the alias name Docsecuritygroup.
     * @return the DOCSECURITYGROUP
     */
    public String getDocsecuritygroup() {
        return (String) getAttributeInternal(DOCSECURITYGROUP);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCSECURITYGROUP using the alias name Docsecuritygroup.
     * @param value value to set the DOCSECURITYGROUP
     */
    public void setDocsecuritygroup(String value) {
        setAttributeInternal(DOCSECURITYGROUP, value);
    }

    /**
     * Gets the attribute value for DOCSOURCEACCOUNT using the alias name Docsourceaccount.
     * @return the DOCSOURCEACCOUNT
     */
    public String getDocsourceaccount() {
        return (String) getAttributeInternal(DOCSOURCEACCOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCSOURCEACCOUNT using the alias name Docsourceaccount.
     * @param value value to set the DOCSOURCEACCOUNT
     */
    public void setDocsourceaccount(String value) {
        setAttributeInternal(DOCSOURCEACCOUNT, value);
    }

    /**
     * Gets the attribute value for DOCUMENTURL using the alias name Documenturl.
     * @return the DOCUMENTURL
     */
    public String getDocumenturl() {
        return (String) getAttributeInternal(DOCUMENTURL);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENTURL using the alias name Documenturl.
     * @param value value to set the DOCUMENTURL
     */
    public void setDocumenturl(String value) {
        setAttributeInternal(DOCUMENTURL, value);
    }


}

