package model.VO;

import java.util.Iterator;
import java.util.List;

import java.util.Map;

import java.util.Set;

import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaItem;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 28 08:03:22 GST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocumentDetailsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DocumentDetailsViewImpl() {
    }
    public void insertDataIntodocumentDetails(List docList){
        this.executeEmptyRowSet();
        Row row = null;
        Map<String,String> documentMap;
        for(int i=0;i<docList.size();i++){
            row = this.createRow();;
            documentMap = (Map<String, String>) docList.get(i);  
            Set set = documentMap.entrySet();
            Iterator itr = set.iterator();
            while(itr.hasNext()){
                Map.Entry entry = (Map.Entry)itr.next();
                String column = (String) entry.getKey();
                row.setAttribute(entry.getKey().toString(), entry.getValue());
                
                
            }
            this.insertRow(row);
        }
        
    }
}

