package model.VO;

import java.math.BigDecimal;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 17 11:07:33 IST 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FeedbackViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_FEEDBACK = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Serialno,
        Neutral,
        Satisfied,
        Unsatisfied,
        VerySatisfied;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int SERIALNO = AttributesEnum.Serialno.index();
    public static final int NEUTRAL = AttributesEnum.Neutral.index();
    public static final int SATISFIED = AttributesEnum.Satisfied.index();
    public static final int UNSATISFIED = AttributesEnum.Unsatisfied.index();
    /**
     * This is the default constructor (do not remove).
     */
    public FeedbackViewRowImpl() {
    }

    /**
     * Gets Feedback entity object.
     * @return the Feedback
     */
    public EntityImpl getFeedback() {
        return (EntityImpl) getEntity(ENTITY_FEEDBACK);
    }

    /**
     * Gets the attribute value for SERIALNO using the alias name Serialno.
     * @return the SERIALNO
     */
    public BigDecimal getSerialno() {
        return (BigDecimal) getAttributeInternal(SERIALNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SERIALNO using the alias name Serialno.
     * @param value value to set the SERIALNO
     */
    public void setSerialno(BigDecimal value) {
        setAttributeInternal(SERIALNO, value);
    }

    /**
     * Gets the attribute value for NEUTRAL using the alias name Neutral.
     * @return the NEUTRAL
     */
    public String getNeutral() {
        return (String) getAttributeInternal(NEUTRAL);
    }

    /**
     * Sets <code>value</code> as attribute value for NEUTRAL using the alias name Neutral.
     * @param value value to set the NEUTRAL
     */
    public void setNeutral(String value) {
        setAttributeInternal(NEUTRAL, value);
    }

    /**
     * Gets the attribute value for SATISFIED using the alias name Satisfied.
     * @return the SATISFIED
     */
    public String getSatisfied() {
        return (String) getAttributeInternal(SATISFIED);
    }

    /**
     * Sets <code>value</code> as attribute value for SATISFIED using the alias name Satisfied.
     * @param value value to set the SATISFIED
     */
    public void setSatisfied(String value) {
        setAttributeInternal(SATISFIED, value);
    }

    /**
     * Gets the attribute value for UNSATISFIED using the alias name Unsatisfied.
     * @return the UNSATISFIED
     */
    public String getUnsatisfied() {
        return (String) getAttributeInternal(UNSATISFIED);
    }

    /**
     * Sets <code>value</code> as attribute value for UNSATISFIED using the alias name Unsatisfied.
     * @param value value to set the UNSATISFIED
     */
    public void setUnsatisfied(String value) {
        setAttributeInternal(UNSATISFIED, value);
    }
}

