package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 19 12:20:38 IST 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FeedbackCalculationVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FeedbackCalculationVOImpl() {
    }
}

