package model.VO;

import java.util.Iterator;
import java.util.Set;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 17 11:07:33 IST 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FeedbackViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FeedbackViewImpl() {
    }
    public void insertFeedbackrows(Set selectedListValues){
        this.executeEmptyRowSet();
        if(!selectedListValues.isEmpty()){
            Iterator ListIterator = selectedListValues.iterator();
            Row row = this.createRow();
            while(ListIterator.hasNext()){
                 String val = (String) ListIterator.next();
                if(val.equalsIgnoreCase("Satisfied")){
                    row.setAttribute("Satisfied", val); 
                }
                if(val.equalsIgnoreCase("Neutral")){
                    row.setAttribute("Neutral", val); 
                }
                if(val.equalsIgnoreCase("Not satisfied")){
                    row.setAttribute("Unsatisfied", val);  
                }
            }
            
            this.insertRow(row);
        }
        
        getDBTransaction().commit();
        
        
    }
}

