package model.VO;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 19 12:20:38 IST 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FeedbackCalculationVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Value,
        ValueCount,
        Percentage;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int VALUE = AttributesEnum.Value.index();
    public static final int VALUECOUNT = AttributesEnum.ValueCount.index();
    public static final int PERCENTAGE = AttributesEnum.Percentage.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FeedbackCalculationVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Value.
     * @return the Value
     */
    public String getValue() {
        return (String) getAttributeInternal(VALUE);
    }

    /**
     * Gets the attribute value for the calculated attribute ValueCount.
     * @return the ValueCount
     */
    public BigDecimal getValueCount() {
        return (BigDecimal) getAttributeInternal(VALUECOUNT);
    }

    /**
     * Gets the attribute value for the calculated attribute Percentage.
     * @return the Percentage
     */
    public BigDecimal getPercentage() {
        return (BigDecimal) getAttributeInternal(PERCENTAGE);
    }
}

