package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 27 14:05:46 GST 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NewCategoryVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NewCategoryVOImpl() {
    }
}

