package model.VO;

import java.math.BigDecimal;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 27 07:55:55 GST 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NewsViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_NEWS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Serialnumber,
        HeadlineEng,
        TagEng,
        SummaryEng,
        HeadlineAr,
        TagAr,
        SummaryAr;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int SERIALNUMBER = AttributesEnum.Serialnumber.index();
    public static final int HEADLINEENG = AttributesEnum.HeadlineEng.index();
    public static final int TAGENG = AttributesEnum.TagEng.index();
    public static final int SUMMARYENG = AttributesEnum.SummaryEng.index();
    public static final int HEADLINEAR = AttributesEnum.HeadlineAr.index();
    public static final int TAGAR = AttributesEnum.TagAr.index();
    public static final int SUMMARYAR = AttributesEnum.SummaryAr.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NewsViewRowImpl() {
    }

    /**
     * Gets News entity object.
     * @return the News
     */
    public EntityImpl getNews() {
        return (EntityImpl) getEntity(ENTITY_NEWS);
    }

    /**
     * Gets the attribute value for SERIALNUMBER using the alias name Serialnumber.
     * @return the SERIALNUMBER
     */
    public BigDecimal getSerialnumber() {
        return (BigDecimal) getAttributeInternal(SERIALNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SERIALNUMBER using the alias name Serialnumber.
     * @param value value to set the SERIALNUMBER
     */
    public void setSerialnumber(BigDecimal value) {
        setAttributeInternal(SERIALNUMBER, value);
    }

    /**
     * Gets the attribute value for HEADLINE_ENG using the alias name HeadlineEng.
     * @return the HEADLINE_ENG
     */
    public String getHeadlineEng() {
        return (String) getAttributeInternal(HEADLINEENG);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADLINE_ENG using the alias name HeadlineEng.
     * @param value value to set the HEADLINE_ENG
     */
    public void setHeadlineEng(String value) {
        setAttributeInternal(HEADLINEENG, value);
    }

    /**
     * Gets the attribute value for TAG_ENG using the alias name TagEng.
     * @return the TAG_ENG
     */
    public String getTagEng() {
        return (String) getAttributeInternal(TAGENG);
    }

    /**
     * Sets <code>value</code> as attribute value for TAG_ENG using the alias name TagEng.
     * @param value value to set the TAG_ENG
     */
    public void setTagEng(String value) {
        setAttributeInternal(TAGENG, value);
    }

    /**
     * Gets the attribute value for SUMMARY_ENG using the alias name SummaryEng.
     * @return the SUMMARY_ENG
     */
    public String getSummaryEng() {
        return (String) getAttributeInternal(SUMMARYENG);
    }

    /**
     * Sets <code>value</code> as attribute value for SUMMARY_ENG using the alias name SummaryEng.
     * @param value value to set the SUMMARY_ENG
     */
    public void setSummaryEng(String value) {
        setAttributeInternal(SUMMARYENG, value);
    }

    /**
     * Gets the attribute value for HEADLINE_AR using the alias name HeadlineAr.
     * @return the HEADLINE_AR
     */
    public String getHeadlineAr() {
        return (String) getAttributeInternal(HEADLINEAR);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADLINE_AR using the alias name HeadlineAr.
     * @param value value to set the HEADLINE_AR
     */
    public void setHeadlineAr(String value) {
        setAttributeInternal(HEADLINEAR, value);
    }

    /**
     * Gets the attribute value for TAG_AR using the alias name TagAr.
     * @return the TAG_AR
     */
    public String getTagAr() {
        return (String) getAttributeInternal(TAGAR);
    }

    /**
     * Sets <code>value</code> as attribute value for TAG_AR using the alias name TagAr.
     * @param value value to set the TAG_AR
     */
    public void setTagAr(String value) {
        setAttributeInternal(TAGAR, value);
    }

    /**
     * Gets the attribute value for SUMMARY_AR using the alias name SummaryAr.
     * @return the SUMMARY_AR
     */
    public String getSummaryAr() {
        return (String) getAttributeInternal(SUMMARYAR);
    }

    /**
     * Sets <code>value</code> as attribute value for SUMMARY_AR using the alias name SummaryAr.
     * @param value value to set the SUMMARY_AR
     */
    public void setSummaryAr(String value) {
        setAttributeInternal(SUMMARYAR, value);
    }
}

