package model.VO;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 26 21:44:24 IST 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NewsTableViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NewsTableViewImpl() {
    }
    
}

