package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 27 07:55:55 GST 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NewsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NewsViewImpl() {
    }
}

