package model.VO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 26 21:44:24 IST 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NewsTableViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_NEWSTABLE = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CrerationDate,
        ExpiryDate,
        HEADLINE_AR,
        HeadlineEng,
        NewsImage,
        NewsTitle,
        Newscategory,
        Serialnumber,
        SummaryAr,
        SummaryEng,
        TagAr,
        TagEng,
        NewCategoryVO1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CRERATIONDATE = AttributesEnum.CrerationDate.index();
    public static final int EXPIRYDATE = AttributesEnum.ExpiryDate.index();
    public static final int HEADLINE_AR = AttributesEnum.HEADLINE_AR.index();
    public static final int HEADLINEENG = AttributesEnum.HeadlineEng.index();
    public static final int NEWSIMAGE = AttributesEnum.NewsImage.index();
    public static final int NEWSTITLE = AttributesEnum.NewsTitle.index();
    public static final int NEWSCATEGORY = AttributesEnum.Newscategory.index();
    public static final int SERIALNUMBER = AttributesEnum.Serialnumber.index();
    public static final int SUMMARYAR = AttributesEnum.SummaryAr.index();
    public static final int SUMMARYENG = AttributesEnum.SummaryEng.index();
    public static final int TAGAR = AttributesEnum.TagAr.index();
    public static final int TAGENG = AttributesEnum.TagEng.index();
    public static final int NEWCATEGORYVO1 = AttributesEnum.NewCategoryVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NewsTableViewRowImpl() {
    }

    /**
     * Gets NewsTable entity object.
     * @return the NewsTable
     */
    public EntityImpl getNewsTable() {
        return (EntityImpl) getEntity(ENTITY_NEWSTABLE);
    }

    /**
     * Gets the attribute value for SERIALNUMBER using the alias name Serialnumber.
     * @return the SERIALNUMBER
     */
    public BigDecimal getSerialnumber() {
        return (BigDecimal) getAttributeInternal(SERIALNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SERIALNUMBER using the alias name Serialnumber.
     * @param value value to set the SERIALNUMBER
     */
    public void setSerialnumber(BigDecimal value) {
        setAttributeInternal(SERIALNUMBER, value);
    }

    /**
     * Gets the attribute value for SUMMARY_AR using the alias name SummaryAr.
     * @return the SUMMARY_AR
     */
    public String getSummaryAr() {
        return (String) getAttributeInternal(SUMMARYAR);
    }

    /**
     * Sets <code>value</code> as attribute value for SUMMARY_AR using the alias name SummaryAr.
     * @param value value to set the SUMMARY_AR
     */
    public void setSummaryAr(String value) {
        setAttributeInternal(SUMMARYAR, value);
    }

    /**
     * Gets the attribute value for SUMMARY_ENG using the alias name SummaryEng.
     * @return the SUMMARY_ENG
     */
    public String getSummaryEng() {
        return (String) getAttributeInternal(SUMMARYENG);
    }

    /**
     * Sets <code>value</code> as attribute value for SUMMARY_ENG using the alias name SummaryEng.
     * @param value value to set the SUMMARY_ENG
     */
    public void setSummaryEng(String value) {
        setAttributeInternal(SUMMARYENG, value);
    }

    /**
     * Gets the attribute value for TAG_AR using the alias name TagAr.
     * @return the TAG_AR
     */
    public String getTagAr() {
        return (String) getAttributeInternal(TAGAR);
    }

    /**
     * Sets <code>value</code> as attribute value for TAG_AR using the alias name TagAr.
     * @param value value to set the TAG_AR
     */
    public void setTagAr(String value) {
        setAttributeInternal(TAGAR, value);
    }

    /**
     * Gets the attribute value for TAG_ENG using the alias name TagEng.
     * @return the TAG_ENG
     */
    public String getTagEng() {
        return (String) getAttributeInternal(TAGENG);
    }

    /**
     * Sets <code>value</code> as attribute value for TAG_ENG using the alias name TagEng.
     * @param value value to set the TAG_ENG
     */
    public void setTagEng(String value) {
        setAttributeInternal(TAGENG, value);
    }

    /**
     * Gets the attribute value for NEWS_TITLE using the alias name NewsTitle.
     * @return the NEWS_TITLE
     */
    public String getNewsTitle() {
        return (String) getAttributeInternal(NEWSTITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for NEWS_TITLE using the alias name NewsTitle.
     * @param value value to set the NEWS_TITLE
     */
    public void setNewsTitle(String value) {
        setAttributeInternal(NEWSTITLE, value);
    }


    /**
     * Gets the attribute value for NEWS_IMAGE using the alias name NewsImage.
     * @return the NEWS_IMAGE
     */
    public BlobDomain getNewsImage() {
        return (BlobDomain) getAttributeInternal(NEWSIMAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for NEWS_IMAGE using the alias name NewsImage.
     * @param value value to set the NEWS_IMAGE
     */
    public void setNewsImage(BlobDomain value) {
        setAttributeInternal(NEWSIMAGE, value);
    }

    /**
     * Gets the attribute value for CRERATION_DATE using the alias name CrerationDate.
     * @return the CRERATION_DATE
     */
    public Timestamp getCrerationDate() {
        return (Timestamp) getAttributeInternal(CRERATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CRERATION_DATE using the alias name CrerationDate.
     * @param value value to set the CRERATION_DATE
     */
    public void setCrerationDate(Timestamp value) {
        setAttributeInternal(CRERATIONDATE, value);
    }

    /**
     * Gets the attribute value for EXPIRY_DATE using the alias name ExpiryDate.
     * @return the EXPIRY_DATE
     */
    public Timestamp getExpiryDate() {
        return (Timestamp) getAttributeInternal(EXPIRYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPIRY_DATE using the alias name ExpiryDate.
     * @param value value to set the EXPIRY_DATE
     */
    public void setExpiryDate(Timestamp value) {
        setAttributeInternal(EXPIRYDATE, value);
    }

    /**
     * Gets the attribute value for HEADLINE_AR using the alias name HEADLINE_AR.
     * @return the HEADLINE_AR
     */
    public String getHEADLINE_AR() {
        return (String) getAttributeInternal(HEADLINE_AR);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADLINE_AR using the alias name HEADLINE_AR.
     * @param value value to set the HEADLINE_AR
     */
    public void setHEADLINE_AR(String value) {
        setAttributeInternal(HEADLINE_AR, value);
    }

    /**
     * Gets the attribute value for HEADLINE_ENG using the alias name HeadlineEng.
     * @return the HEADLINE_ENG
     */
    public String getHeadlineEng() {
        return (String) getAttributeInternal(HEADLINEENG);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADLINE_ENG using the alias name HeadlineEng.
     * @param value value to set the HEADLINE_ENG
     */
    public void setHeadlineEng(String value) {
        setAttributeInternal(HEADLINEENG, value);
    }

    /**
     * Gets the attribute value for NEWSCATEGORY using the alias name Newscategory.
     * @return the NEWSCATEGORY
     */
    public String getNewscategory() {
        return (String) getAttributeInternal(NEWSCATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for NEWSCATEGORY using the alias name Newscategory.
     * @param value value to set the NEWSCATEGORY
     */
    public void setNewscategory(String value) {
        setAttributeInternal(NEWSCATEGORY, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> NewCategoryVO1.
     */
    public RowSet getNewCategoryVO1() {
        return (RowSet) getAttributeInternal(NEWCATEGORYVO1);
    }
}

