package model.VO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 23 14:16:20 GST 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProjectTimelineNewViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_PROJECTTIMELINENEW = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ArabicPhaseDetails,
        Serialnumber,
        ArabicPhaseEndDate,
        ArabicPhaseName,
        ArabicPhaseStartDate,
        ArabicPhaseno,
        EnglishPhaseDetails,
        EnglishPhaseEndDate,
        EnglishPhaseName,
        EnglishPhaseStartDate,
        EnglishPhaseno,
        ArabicCurrentPhase,
        CurrentPhase;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ARABICPHASEDETAILS = AttributesEnum.ArabicPhaseDetails.index();
    public static final int SERIALNUMBER = AttributesEnum.Serialnumber.index();
    public static final int ARABICPHASEENDDATE = AttributesEnum.ArabicPhaseEndDate.index();
    public static final int ARABICPHASENAME = AttributesEnum.ArabicPhaseName.index();
    public static final int ARABICPHASESTARTDATE = AttributesEnum.ArabicPhaseStartDate.index();
    public static final int ARABICPHASENO = AttributesEnum.ArabicPhaseno.index();
    public static final int ENGLISHPHASEDETAILS = AttributesEnum.EnglishPhaseDetails.index();
    public static final int ENGLISHPHASEENDDATE = AttributesEnum.EnglishPhaseEndDate.index();
    public static final int ENGLISHPHASENAME = AttributesEnum.EnglishPhaseName.index();
    public static final int ENGLISHPHASESTARTDATE = AttributesEnum.EnglishPhaseStartDate.index();
    public static final int ENGLISHPHASENO = AttributesEnum.EnglishPhaseno.index();
    public static final int ARABICCURRENTPHASE = AttributesEnum.ArabicCurrentPhase.index();
    public static final int CURRENTPHASE = AttributesEnum.CurrentPhase.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProjectTimelineNewViewRowImpl() {
    }

    /**
     * Gets ProjectTimelineNew entity object.
     * @return the ProjectTimelineNew
     */
    public EntityImpl getProjectTimelineNew() {
        return (EntityImpl) getEntity(ENTITY_PROJECTTIMELINENEW);
    }

    /**
     * Gets the attribute value for ARABIC_PHASE_DETAILS using the alias name ArabicPhaseDetails.
     * @return the ARABIC_PHASE_DETAILS
     */
    public String getArabicPhaseDetails() {
        return (String) getAttributeInternal(ARABICPHASEDETAILS);
    }

    /**
     * Sets <code>value</code> as attribute value for ARABIC_PHASE_DETAILS using the alias name ArabicPhaseDetails.
     * @param value value to set the ARABIC_PHASE_DETAILS
     */
    public void setArabicPhaseDetails(String value) {
        setAttributeInternal(ARABICPHASEDETAILS, value);
    }

    /**
     * Gets the attribute value for SERIALNUMBER using the alias name Serialnumber.
     * @return the SERIALNUMBER
     */
    public BigDecimal getSerialnumber() {
        return (BigDecimal) getAttributeInternal(SERIALNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SERIALNUMBER using the alias name Serialnumber.
     * @param value value to set the SERIALNUMBER
     */
    public void setSerialnumber(BigDecimal value) {
        setAttributeInternal(SERIALNUMBER, value);
    }

    /**
     * Gets the attribute value for ARABIC_PHASE_END_DATE using the alias name ArabicPhaseEndDate.
     * @return the ARABIC_PHASE_END_DATE
     */
    public Timestamp getArabicPhaseEndDate() {
        return (Timestamp) getAttributeInternal(ARABICPHASEENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ARABIC_PHASE_END_DATE using the alias name ArabicPhaseEndDate.
     * @param value value to set the ARABIC_PHASE_END_DATE
     */
    public void setArabicPhaseEndDate(Timestamp value) {
        setAttributeInternal(ARABICPHASEENDDATE, value);
    }

    /**
     * Gets the attribute value for ARABIC_PHASE_NAME using the alias name ArabicPhaseName.
     * @return the ARABIC_PHASE_NAME
     */
    public String getArabicPhaseName() {
        return (String) getAttributeInternal(ARABICPHASENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ARABIC_PHASE_NAME using the alias name ArabicPhaseName.
     * @param value value to set the ARABIC_PHASE_NAME
     */
    public void setArabicPhaseName(String value) {
        setAttributeInternal(ARABICPHASENAME, value);
    }

    /**
     * Gets the attribute value for ARABIC_PHASE_START_DATE using the alias name ArabicPhaseStartDate.
     * @return the ARABIC_PHASE_START_DATE
     */
    public Timestamp getArabicPhaseStartDate() {
        return (Timestamp) getAttributeInternal(ARABICPHASESTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ARABIC_PHASE_START_DATE using the alias name ArabicPhaseStartDate.
     * @param value value to set the ARABIC_PHASE_START_DATE
     */
    public void setArabicPhaseStartDate(Timestamp value) {
        setAttributeInternal(ARABICPHASESTARTDATE, value);
    }

    /**
     * Gets the attribute value for ARABIC_PHASENO using the alias name ArabicPhaseno.
     * @return the ARABIC_PHASENO
     */
    public String getArabicPhaseno() {
        return (String) getAttributeInternal(ARABICPHASENO);
    }

    /**
     * Sets <code>value</code> as attribute value for ARABIC_PHASENO using the alias name ArabicPhaseno.
     * @param value value to set the ARABIC_PHASENO
     */
    public void setArabicPhaseno(String value) {
        setAttributeInternal(ARABICPHASENO, value);
    }

    /**
     * Gets the attribute value for ENGLISH_PHASE_DETAILS using the alias name EnglishPhaseDetails.
     * @return the ENGLISH_PHASE_DETAILS
     */
    public String getEnglishPhaseDetails() {
        return (String) getAttributeInternal(ENGLISHPHASEDETAILS);
    }

    /**
     * Sets <code>value</code> as attribute value for ENGLISH_PHASE_DETAILS using the alias name EnglishPhaseDetails.
     * @param value value to set the ENGLISH_PHASE_DETAILS
     */
    public void setEnglishPhaseDetails(String value) {
        setAttributeInternal(ENGLISHPHASEDETAILS, value);
    }

    /**
     * Gets the attribute value for ENGLISH_PHASE_END_DATE using the alias name EnglishPhaseEndDate.
     * @return the ENGLISH_PHASE_END_DATE
     */
    public Timestamp getEnglishPhaseEndDate() {
        return (Timestamp) getAttributeInternal(ENGLISHPHASEENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ENGLISH_PHASE_END_DATE using the alias name EnglishPhaseEndDate.
     * @param value value to set the ENGLISH_PHASE_END_DATE
     */
    public void setEnglishPhaseEndDate(Timestamp value) {
        setAttributeInternal(ENGLISHPHASEENDDATE, value);
    }

    /**
     * Gets the attribute value for ENGLISH_PHASE_NAME using the alias name EnglishPhaseName.
     * @return the ENGLISH_PHASE_NAME
     */
    public String getEnglishPhaseName() {
        return (String) getAttributeInternal(ENGLISHPHASENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ENGLISH_PHASE_NAME using the alias name EnglishPhaseName.
     * @param value value to set the ENGLISH_PHASE_NAME
     */
    public void setEnglishPhaseName(String value) {
        setAttributeInternal(ENGLISHPHASENAME, value);
    }

    /**
     * Gets the attribute value for ENGLISH_PHASE_START_DATE using the alias name EnglishPhaseStartDate.
     * @return the ENGLISH_PHASE_START_DATE
     */
    public Timestamp getEnglishPhaseStartDate() {
        return (Timestamp) getAttributeInternal(ENGLISHPHASESTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ENGLISH_PHASE_START_DATE using the alias name EnglishPhaseStartDate.
     * @param value value to set the ENGLISH_PHASE_START_DATE
     */
    public void setEnglishPhaseStartDate(Timestamp value) {
        setAttributeInternal(ENGLISHPHASESTARTDATE, value);
    }

    /**
     * Gets the attribute value for ENGLISH_PHASENO using the alias name EnglishPhaseno.
     * @return the ENGLISH_PHASENO
     */
    public String getEnglishPhaseno() {
        return (String) getAttributeInternal(ENGLISHPHASENO);
    }

    /**
     * Sets <code>value</code> as attribute value for ENGLISH_PHASENO using the alias name EnglishPhaseno.
     * @param value value to set the ENGLISH_PHASENO
     */
    public void setEnglishPhaseno(String value) {
        setAttributeInternal(ENGLISHPHASENO, value);
    }

    /**
     * Gets the attribute value for ARABIC_CURRENT_PHASE using the alias name ArabicCurrentPhase.
     * @return the ARABIC_CURRENT_PHASE
     */
    public String getArabicCurrentPhase() {
        return (String) getAttributeInternal(ARABICCURRENTPHASE);
    }

    /**
     * Sets <code>value</code> as attribute value for ARABIC_CURRENT_PHASE using the alias name ArabicCurrentPhase.
     * @param value value to set the ARABIC_CURRENT_PHASE
     */
    public void setArabicCurrentPhase(String value) {
        setAttributeInternal(ARABICCURRENTPHASE, value);
    }

    /**
     * Gets the attribute value for CURRENT_PHASE using the alias name CurrentPhase.
     * @return the CURRENT_PHASE
     */
    public String getCurrentPhase() {
        return (String) getAttributeInternal(CURRENTPHASE);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENT_PHASE using the alias name CurrentPhase.
     * @param value value to set the CURRENT_PHASE
     */
    public void setCurrentPhase(String value) {
        setAttributeInternal(CURRENTPHASE, value);
    }


}

