package model.EO.common;

import java.math.BigDecimal;

import java.util.ArrayList;
import java.util.List;

import java.util.Map;
import java.util.Set;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 27 08:19:04 GST 2024
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void setDocumentDetailsData(List documentLists);


    void searchbook(String bookname, String bookTitle);

    void resetSearchbook();

    void searchNews(BigDecimal serialId);

    void insertFeedbackValues(Set selectValuesList);

    Map getNewsFromDB();

    Integer getLatestNewsSerialNumber();

    String deleteNews(Integer serialNumber);

    String updateNews(ArrayList<String> news);

    String addNews(ArrayList<String> news);

    String callGetFeedbackFlag(String userId);

    String addUserfeedback(String user_id, String user_name, String Glad, String happy, String Neutral,
                           String Dissatisfied, String ExtremelyDissatisfied, String user_comment);

    Map getTimeLineFromDB();
}

